package app.justfyi

import androidx.compose.ui.window.ComposeUIViewController
import app.justfyi.di.IosAppGraph
import app.justfyi.di.createIosAppGraph
import app.justfyi.firebase.IosFirebaseInitializer
import app.justfyi.util.Logger
import platform.UIKit.UIViewController

/**
 * Main entry point for the iOS application.
 *
 * This function creates the main UIViewController that hosts the Compose UI.
 * It handles:
 * 1. Metro DI graph initialization
 * 2. Firebase initialization
 * 3. Lifecycle manager setup for BLE foreground/background handling
 * 4. Push notification capability setup
 * 5. Deep linking configuration
 *
 * The initialization order is important:
 * 1. First, initialize Firebase (required before any Firebase operations)
 * 2. Then, initialize Metro DI graph (provides all dependencies)
 * 3. Finally, set up lifecycle manager (uses DI-provided BleRepository)
 *
 * Usage from Swift:
 * ```swift
 * import UIKit
 * import ComposeApp
 *
 * @main
 * struct JustFyiApp: App {
 *     var body: some Scene {
 *         WindowGroup {
 *             ComposeView()
 *         }
 *     }
 * }
 *
 * struct ComposeView: UIViewControllerRepresentable {
 *     func makeUIViewController(context: Context) -> UIViewController {
 *         return MainViewControllerKt.MainViewController()
 *     }
 *
 *     func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
 * }
 * ```
 */
fun MainViewController(): UIViewController {
    // Initialize the app before creating the Compose UI
    initializeApp()

    return ComposeUIViewController {
        App()
    }
}

/**
 * Initializes the iOS application components.
 *
 * This function sets up:
 * 1. Firebase SDK via GitLive
 * 2. Metro DI graph with all platform-specific modules
 * 3. iOS lifecycle manager for BLE management
 */
private fun initializeApp() {
    Logger.d(TAG, "Initializing iOS application")

    initializeFirebase()
    initializeDependencyGraph()
    initializeLifecycleManager()

    Logger.d(TAG, "iOS application initialization complete")
}

/**
 * Initializes Firebase using GitLive SDK.
 *
 * Firebase must be initialized before any Firebase operations.
 * Uses the GoogleService-Info.plist configuration file.
 */
private fun initializeFirebase() {
    try {
        Logger.d(TAG, "Initializing Firebase")
        val initializer = IosFirebaseInitializer()
        initializer.initialize()
        Logger.d(TAG, "Firebase initialized successfully")
    } catch (e: Exception) {
        Logger.e(TAG, "Failed to initialize Firebase", e)
        // Continue even if Firebase fails - the app may work in limited capacity
    }
}

/**
 * Initializes the Metro DI graph.
 *
 * Creates the IosAppGraph with all platform-specific modules:
 * - IosProviders: Platform services (clipboard, locale)
 * - IosFirebaseModule: Firebase via GitLive SDK
 * - IosBleModule: Core Bluetooth BLE components
 * - IosRepositoryModule: Repository implementations
 * - IosDatabaseModule: SQLDelight with NativeSqliteDriver
 *
 * Note: Metro generates the actual graph implementation at compile time.
 * The createIosAppGraph() function is generated by Metro KSP.
 */
private fun initializeDependencyGraph() {
    try {
        Logger.d(TAG, "Initializing Metro DI graph")

        // Check if already initialized
        if (IosAppGraph.isInitialized()) {
            Logger.d(TAG, "DI graph already initialized")
            return
        }

        // Create the Metro-generated graph implementation
        // Metro generates createIosAppGraph() based on @DependencyGraph annotation
        val graph = createIosAppGraph()
        IosAppGraph.initialize(graph)

        Logger.d(TAG, "Metro DI graph initialized successfully")
    } catch (e: Exception) {
        Logger.e(TAG, "Failed to initialize DI graph", e)
        throw IllegalStateException("Cannot start app without DI graph", e)
    }
}

/**
 * Initializes the lifecycle manager for BLE foreground/background handling.
 *
 * The lifecycle manager:
 * - Starts BLE discovery when app enters foreground
 * - Stops BLE discovery when app enters background
 * - Registers for UIApplication lifecycle notifications
 */
private fun initializeLifecycleManager() {
    try {
        Logger.d(TAG, "Initializing lifecycle manager")

        // Skip if DI graph is not initialized
        if (!IosAppGraph.isInitialized()) {
            Logger.w(TAG, "Cannot initialize lifecycle manager without DI graph")
            return
        }

        // Get BleRepository from DI graph
        val graph = IosAppGraph.getInstance()

        // Note: BleRepository is accessed via the navigation graph
        // For lifecycle management, we'll initialize when the graph is available
        // The actual BLE operations will start when the app enters foreground

        Logger.d(TAG, "Lifecycle manager setup deferred to first screen")
    } catch (e: Exception) {
        Logger.e(TAG, "Failed to initialize lifecycle manager", e)
        // Continue - BLE will not auto-start/stop on lifecycle changes
    }
}

private const val TAG = "MainViewController"
